version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - run: npm install
      - run: npm run test

  production:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run deploy --env=production